/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'activity-id-report': RouteRecordInfo<'activity-id-report', '/activity/:id/report', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'activity-id-view-report': RouteRecordInfo<'activity-id-view-report', '/activity/:id/view-report', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'activity-list': RouteRecordInfo<'activity-list', '/activity/list', Record<never, never>, Record<never, never>>,
    'customers-list': RouteRecordInfo<'customers-list', '/customers/list', Record<never, never>, Record<never, never>>,
    'customers-view-customer-id': RouteRecordInfo<'customers-view-customer-id', '/customers/view/:customerId', { customerId: ParamValue<true> }, { customerId: ParamValue<false> }>,
    'customers-view-customer-id-invoice-invoice-id': RouteRecordInfo<'customers-view-customer-id-invoice-invoice-id', '/customers/view/:customerId/invoice/:invoiceId', { customerId: ParamValue<true>, invoiceId: ParamValue<true> }, { customerId: ParamValue<false>, invoiceId: ParamValue<false> }>,
    'customers-view-customer-id-item-item-id': RouteRecordInfo<'customers-view-customer-id-item-item-id', '/customers/view/:customerId/item/:itemId', { customerId: ParamValue<true>, itemId: ParamValue<true> }, { customerId: ParamValue<false>, itemId: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'sales-list': RouteRecordInfo<'sales-list', '/sales/list', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'users-list': RouteRecordInfo<'users-list', '/users/list', Record<never, never>, Record<never, never>>,
  }
}
