/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'activity-id-report': RouteRecordInfo<
      'activity-id-report',
      '/activity/:id/report',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'activity-id-report-edit': RouteRecordInfo<
      'activity-id-report-edit',
      '/activity/:id/report/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'activity-id-view-report': RouteRecordInfo<
      'activity-id-view-report',
      '/activity/:id/view-report',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'activity-deleted': RouteRecordInfo<
      'activity-deleted',
      '/activity/deleted',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'activity-list': RouteRecordInfo<
      'activity-list',
      '/activity/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-error-logs': RouteRecordInfo<
      'admin-error-logs',
      '/admin/error-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-list': RouteRecordInfo<
      'customers-list',
      '/customers/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-view-customer-id': RouteRecordInfo<
      'customers-view-customer-id',
      '/customers/view/:customerId',
      { customerId: ParamValue<true> },
      { customerId: ParamValue<false> },
      | never
    >,
    'customers-view-customer-id-invoice-invoice-id': RouteRecordInfo<
      'customers-view-customer-id-invoice-invoice-id',
      '/customers/view/:customerId/invoice/:invoiceId',
      { customerId: ParamValue<true>, invoiceId: ParamValue<true> },
      { customerId: ParamValue<false>, invoiceId: ParamValue<false> },
      | never
    >,
    'customers-view-customer-id-item-item-id': RouteRecordInfo<
      'customers-view-customer-id-item-item-id',
      '/customers/view/:customerId/item/:itemId',
      { customerId: ParamValue<true>, itemId: ParamValue<true> },
      { customerId: ParamValue<false>, itemId: ParamValue<false> },
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'profile': RouteRecordInfo<
      'profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sales-list': RouteRecordInfo<
      'sales-list',
      '/sales/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'second-page': RouteRecordInfo<
      'second-page',
      '/second-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-list': RouteRecordInfo<
      'users-list',
      '/users/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'root'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
      pathParamNames:
        | 'error'
    }
    'src/pages/activity/[id]/report/index.vue': {
      routes:
        | 'activity-id-report'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/activity/[id]/report/edit/index.vue': {
      routes:
        | 'activity-id-report-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/activity/[id]/view-report/index.vue': {
      routes:
        | 'activity-id-view-report'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/activity/deleted/index.vue': {
      routes:
        | 'activity-deleted'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/activity/list/index.vue': {
      routes:
        | 'activity-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/error-logs/index.vue': {
      routes:
        | 'admin-error-logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/customers/list/index.vue': {
      routes:
        | 'customers-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/customers/view/[customerId]/index.vue': {
      routes:
        | 'customers-view-customer-id'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/customers/view/[customerId]/invoice/[invoiceId]/index.vue': {
      routes:
        | 'customers-view-customer-id-invoice-invoice-id'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/customers/view/[customerId]/item/[itemId]/index.vue': {
      routes:
        | 'customers-view-customer-id-item-item-id'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | 'profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sales/list/index.vue': {
      routes:
        | 'sales-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/second-page.vue': {
      routes:
        | 'second-page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/list/index.vue': {
      routes:
        | 'users-list'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
