name: Deploy Vue 3 to Production

on:
  push:
    branches: [ "release/v1" ]
  pull_request:
    branches: [ "release/v1" ]

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/v1'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Create .env.production file
      run: echo "${{ secrets.VITE_ENV_PROD }}" > .env.production
    
    - name: Inject App Version to .env file
      run: |
        VERSION=$(git describe --abbrev=0 --tags)
        echo "VITE_APP_VERSION=${VERSION}" >> .env.production
        echo "APP VERSION: ${VERSION}"
    
    - name: Show .env files in runner
      run: |
        ls -al
        echo "--- .env.production ---"
        cat .env.production || echo "NOT FOUND"
# Skip for now
    # - name: Run type check & lint
    #   run: |
    #     npm run typecheck
    #     npm run lint

    - name: Build project
      run: npm run build

    - name: Deploy to server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 30122
        source: "dist/*"
        target: "/home/sps-saleshub"
