name: Vue Deploy Only

on:
  push:
    branches: [ "release/v1" ]
  pull_request:
    branches: [ "release/v1" ]

jobs:
  deploy:
    name: Deploy Vue to Production Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/v1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Vue app via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 30122
          script: |
            echo "🚀 Deploying Vue project..."
            cd /home/sps-saleshub

            echo "🔄 Pull latest code..."
            git pull origin release/v1

            echo "📦 Installing dependencies..."
            npm install --legacy-peer-deps

            echo "🛠️ Building project with production env..."
            npm run build -- --mode production

            echo "✅ Build completed."
